# -*- coding: utf-8 -*-
"""tensorflow_EX0.ipynb

Automatically generated by Colaboratory.

"""

from __future__ import division, print_function, unicode_literals
import tensorflow as tf
import numpy as np
from time import time

"""Construct a tensorflow graph to calculate the area of a circle. Use:
    tf.constant to define a constant named pi, which will be equal to 3.14. And 
    tf.Variable to set the radius (use your favorite radius value).
    Don't forget to initialize your variables.\
"""

tf.reset_default_graph()
pi = tf.constant(3.14)
r = tf.Variable(2, dtype=tf.float32)
circ_area_op = np.multiply((r ** 2), pi)

with tf.Session() as sess:
  sess.run(r.initializer)
  res = sess.run(circ_area_op)
  print('circle area with variable:', res)

"""Repeat the same exercise as above -- calculating the area of a circle using tensorflow, but this time use:
   tf.placeholder to hold the radius value (instead of using a variable)."""

tf.reset_default_graph()
pi = tf.constant(3.14)
r = tf.placeholder(tf.float32)
circ_area_op = np.multiply((r ** 2), pi)
with tf.Session() as sess2:

  res = sess2.run(circ_area_op, {r: 2})
  print('circle area with variable:', res)