"""
This code tries to decrypt an output generated by encrypt() of encrypt_for_decrypt_2.py.

Find and fix the bug(s)!

Author: Omer Rosenbaum
"""
SECRET = "30,Q|{4-s|tr-|-r-dnpur-n{q-r-Ornx}|v{-ny|{t-ur-n;;;"


def decrypt(encrypted):
    (offset, encrypted_string) = encrypted.split(',')
    offset = (int(offset)-4)//2
    decrypted_string = ""
    for character in encrypted_string:
        decrypted_string += chr(ord(character)-offset)

    return decrypted_string

if __name__ == "__main__":
    print(decrypt(SECRET))